In [41]:
import numpy as np

In [42]:
A	=	np.array([0.2, 0.4, 0.7, 0.8])
B	=	np.array([0.1, 0.8, 0.2, 0.3])

In [43]:
def	union(A,B)	:	
    return	np.maximum(A,B)

In [44]:
def	intersection(A,B)	:	
    return	np.minimum(A,B)

In [45]:
def	complement(A)	:	
    return	1-A

In [46]:
def	difference(A,B)	:
    return	np.maximum(A-B, 0)

In [47]:
def	cartesian_product(A,B):
    return	np.outer(A,	B)

In [48]:
def	max_min_composition(R1,	R2):
    return	np.maximum(np.minimum(R1,R2), 0)

In [49]:
R1	=	cartesian_product(A,B)
R2	=	cartesian_product(B,A)
result	=	max_min_composition(R1,R2)

In [50]:
print("+" * 54)
print("Fuzzy operations".center(54))
print("+" * 54)
print(f"| Union	of A and B          :	{union(A,B)}|")
print(f"| Intersection of A and B	:	{intersection(A,B)}|")
print(f"| Complement of A and B		:	{complement(A)}|")
print(f"| Difference of A and B	    :	{difference(A,B)}")	
print(f"cartesian_product of A and B	:	\n{R1}")
print(f"cartesian_product of B and A	:	\n{R2}")
print(f"max_min_composition of A and B	:	\n{result}")
print("+" * 54)
 
 

++++++++++++++++++++++++++++++++++++++++++++++++++++++
                   Fuzzy operations                   
++++++++++++++++++++++++++++++++++++++++++++++++++++++
| Union	of A and B          :	[0.2 0.8 0.7 0.8]|
| Intersection of A and B	:	[0.1 0.4 0.2 0.3]|
| Complement of A and B		:	[0.8 0.6 0.3 0.2]|
| Difference of A and B	    :	[0.1 0.  0.5 0.5]
cartesian_product of A and B	:	
[[0.02 0.16 0.04 0.06]
 [0.04 0.32 0.08 0.12]
 [0.07 0.56 0.14 0.21]
 [0.08 0.64 0.16 0.24]]
cartesian_product of B and A	:	
[[0.02 0.04 0.07 0.08]
 [0.16 0.32 0.56 0.64]
 [0.04 0.08 0.14 0.16]
 [0.06 0.12 0.21 0.24]]
max_min_composition of A and B	:	
[[0.02 0.04 0.04 0.06]
 [0.04 0.32 0.08 0.12]
 [0.04 0.08 0.14 0.16]
 [0.06 0.12 0.16 0.24]]
++++++++++++++++++++++++++++++++++++++++++++++++++++++
